name: OrangeFox Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OrangeFox Build
        uses: UWU-TEAM/UWU-OrangeFox-Builder@v1.0.0
        with:
          USER_NAME: "RobotsAreCrazy"
          USER_EMAIL: "robotsarecrazy@github.com"
          DEVICE_TREE: "https://github.com/RobotsAreCrazy/custom_recovery_tree_samsung_gta9p"
          DEVICE_TREE_BRANCH: "twrp-12.1"
          DEVICE_PATH: "device/samsung/gta9p"
          DEVICE_NAME: "gta9p"
          BUILD_TARGET: "recovery"
          GH_RELEASE: "true"
